################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-deploy
spec:
  selector:
    matchLabels:
      mylabel: spring-petclinic-po
  template:
    metadata:
      labels:
        mylabel: spring-petclinic-po
    spec:
      containers:
      -
        image: secobau/spring-petclinic:0.6
        name: spring-petclinic-container
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
  ports:
  -
    port: 8080
  selector:
    mylabel: spring-petclinic-po
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: spring-petclinic-route
spec:
  to:
    kind: Service
    name: spring-petclinic
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
################################################################################
